language: php

php:
    - 5.2
    - 5.3
    - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.5.1 WP_MULTISITE=0
    - WP_VERSION=3.4.2 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=1
    - WP_VERSION=3.4.2 WP_MULTISITE=1

before_install:
    - git submodule update --init --recursive

before_script:
    - wget -nv https://raw.github.com/benbalter/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh

script: phpunit
